# KNOWLEDGE LAND COLLEGE CBT v6.3
# Powered by FEMZYK | OLUFEMI BENUA KERIPE

supabase.url=https://aqircycpctadgvbqsadf.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxaXJjeWNwY3RhZGd2YnFzYWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxNDM0OTMsImV4cCI6MjA5NzcxOTQ5M30.mn9pn4bmx8R860K2KZx-MEe-G0U7o4ZYZxwwO6p7sjg

# Pooler connection only - port 5432 blocked by network
supabase.db.pooler.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres
supabase.db.pooler.user=postgres.aqircycpctadgvbqsadf
supabase.db.pooler.password=Femi6140@gmail.com

# Offline H2 cache
h2.url=jdbc:h2:file:./klc_cache/klc_local;AUTO_SERVER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;MODE=PostgreSQL
h2.user=sa
h2.password=

# Registration codes
code.super_admin=FEMZYK ENTERPRISES LTD
code.admin=FEMZYK
code.student=FEMZYKENTLTD

# School
school.name=KNOWLEDGE LAND COLLEGE
school.motto=Knowledge is Power
school.principal=OLUFEMI BENUA KERIPE

# Proctoring
proctor.max_strikes=3
proctor.fullscreen=true

# Email / SMTP - Brevo (300 emails/day free)
smtp.host=smtp-relay.brevo.com
smtp.port=587
smtp.user=b07bf2001@smtp-brevo.com
smtp.pass=xsmtpsib-50b6008a735b66c92428ba57952f4aecf816bbed597d87210a71c9f0bc56da73-hUZoxnbEzTPWhztF
smtp.from.name=KNOWLEDGE LAND COLLEGE CBT
smtp.from.email=femzykenterprisesltd@gmail.com

# SMS - Termii Nigeria - Optional
sms.provider=
sms.api_key=